default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB_DEV'] %>

test:
  <<: *default
  host: localhost
  port: 5432
  database: <%= ENV['POSTGRES_DB_TEST'] %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD_TEST'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB_PROD'] %>
  username: <%= ENV['POSTGRES_USER_PROD'] %>
  password: <%= ENV['POSTGRES_PASSWORD_PROD'] %>
