default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exchange_rate_development

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: exchange_rate_production
  username: exchange_rate
  password: <%= ENV['POSTGRES_PASSWORD'] %>
