name: Test and Deploy with GitHub Actions 🚀

on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: exchange_rate_test

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run bundle install
        run: |
          bundle config --local path vendor/bundle
          bundle config --local without production
          bundle install

      - run: RAILS_ENV=test bundle exec rails assets:precompile

      - run: bundle exec rspec
